# Generated by Django 4.2.8 on 2024-01-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_useraccount_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="role",
            field=models.CharField(default="user", max_length=50),
        ),
    ]
