# Generated by Django 4.2.8 on 2024-01-04 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("employees", "0001_initial"),
        ("visitors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visit_type", models.CharField(max_length=255)),
                ("purpose", models.TextField()),
                ("checkin", models.DateTimeField(auto_now_add=True)),
                ("checkout", models.DateTimeField(blank=True, null=True)),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employees.employee",
                    ),
                ),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visitors.visitor",
                    ),
                ),
            ],
            options={
                "ordering": ["-checkin"],
            },
        ),
    ]
