# Generated by Django 4.2.8 on 2024-01-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="checkout",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
