# Generated by Django 4.2.8 on 2024-01-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="purpose",
            field=models.CharField(max_length=255),
        ),
    ]
