# Generated by Django 4.2.8 on 2024-01-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0002_alter_visit_checkout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="checkout",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
