# Generated by Django 4.2.8 on 2024-01-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visits", "0002_alter_visit_purpose"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="visit",
            options={},
        ),
        migrations.AlterField(
            model_name="visit",
            name="host",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="visit",
            name="visitor",
            field=models.CharField(max_length=255),
        ),
    ]
