# Generated by Django 4.2.8 on 2024-01-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tm",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Phone", models.CharField(max_length=20)),
                ("Email", models.EmailField(max_length=254)),
            ],
        ),
    ]
